### ISSUE TITLE
[bug?] Missing characters after download

### ISSUE THREAD

**Issue by MrQuerter** [aandrew-me/ytDownloader#64] opened 2022-11-08 22:20 UTC
Hi.
I noticed that after downloading something, there are characters that are missing and spaces are replaced with underscore.
While replacing underscores isn't a problem, the missing characters are. yt-dlp and 4k video downloader usually keep most of them.

& ) ( ! - these are the ones that I know are getting deleted. If it is because of windows forbidden file name characters then could we get an option to keep them it in linux versions? You already have an option that only works for linux so it wouldn't be out of place

**Comment by MrQuerter** [comment] 2022-11-08 22:36
Forgot about one particularly annoying: ' apostrophe. It's used quite often in titles.

**Comment by aandrew-me** [comment] 2022-11-09 03:07
Hey.
This is not a bug. You're right, I had implemented it because of 'forbidden file name characters'. I will fix it.
Thanks

**Comment by aandrew-me** [comment] 2022-11-09 07:47
The forbidden printable ASCII characters are:
- Linux/Unix:
```
 / (forward slash)
```
- Windows
```
  < (less than)
  > (greater than)
  : (colon - sometimes works, but is actually NTFS Alternate Data Streams)
  " (double quote)
  / (forward slash)
  \ (backslash)
  | (vertical bar or pipe)
  ? (question mark)
  * (asterisk)
```

That's how it will be filtered.

**Comment by aandrew-me** [comment] 2022-11-09 11:41
I will do some testing and an update will be available soon.

**Comment by MrQuerter** [comment] 2022-11-09 23:55
Just some feedback. I overridden the renderer.js that is provided in flatpak version with your changes and the characters now stay.

Though there is one issue with ' apostrophe. That being if your download has it in the name then the "File saved. Click to Open" doesn't work.

**Comment by aandrew-me** [comment] 2022-11-10 09:26
Thank you very much for testing things.
Regarding double quote, right, I will have to filter it too as I am using double quotes for strings.

But in case of an apostrophe I couldn't reproduce such a problem. Can you please post the video url of the video with which you faced problem?

**Comment by MrQuerter** [comment] 2022-11-10 09:55
Basically any that has apostrophe/s in title, but here you go: https://www.youtube.com/watch?v=hY4yspCQRaM

Tested both on flatpak and AppImage. It's not a big issue since the video is downloaded without problems it's just that you can't open the location from the program.

**Comment by aandrew-me** [comment] 2022-11-10 10:13
I get it. This problem will not be there. I believe I fixed it

**Comment by MrQuerter** [comment] 2022-11-10 10:25
Yes, can confirm.
The ones with apostrophe now open the location and the apostrophe stays in the file name and the ones with double quotes in title don't have them in the file name, but don't throw any errors and can be downloaded.
Thank you for that. I guess you can close this issue now, unless you are leaving it after the update releases.

**Comment by aandrew-me** [comment] 2022-11-10 10:29
Great!
Thanks again for testing. I am closing it for now. I will do some testing and then release the update.

**Closed by aandrew-me** 2022-11-10 10:29 UTC
