### ISSUE TITLE
file format issues that were previously fine

### ISSUE THREAD

**Issue by splace** [aandrew-me/ytDownloader#188] opened 2024-02-13 22:49 UTC
**Bug Description**
latest (and previous?) having various new issues with formats:

- downloads AV1 when h264 selected and available.
- default not being used.
- sizes (mostly) no longer displayed.
- many identical formats listed

**Info (please complete the following information):**
 - Operating system:fedora
 - App version:3.17.1
 - Package version (flatpak/snap/other):flatpak

**Comment by aandrew-me** [comment] 2024-02-17 06:43
1. By h264 I assume you meant AVC1. I did some tests and didn't find any problem, so you have to provide more details and steps to reproduce
2. What do you mean by that? The 'Preferred' formats are selected automatically once you get the video info. 
3. Yes, not a bug
4. Yes, I am just displaying the items provided by Youtube, so not a bug

**Comment by splace** [comment] 2024-02-20 23:54
1. upon testing i discovered i get h264 when i select "unknown size" so at least i can still use.

**Comment by splace** [comment] 2024-02-20 23:58
2.  here are my settings....(requested not selected)

![Screenshot from 2024-02-20 23-50-17](https://github.com/aandrew-me/ytDownloader/assets/1234848/a7bb776e-f682-4470-a15b-704cfdf766af)

here are the 100+ options, including 10+ of the requested size....

![Screenshot from 2024-02-20 23-50-54](https://github.com/aandrew-me/ytDownloader/assets/1234848/8f100d5a-2bae-45f6-a398-40ff3c97e0b5)

**Comment by aandrew-me** [comment] 2024-02-21 04:33
1. In Preferences there is an option called show more options, it shows the codecs

**Comment by splace** [comment] 2024-02-22 20:57
https://www.bbc.co.uk/iplayer/episode/m001gp02/dynasties-macaque-monkeys-in-the-mountains-a-dynasties-special

this doesn't set 720p as default.

with the "show more options" i see 'avc3' maybe something to do with it?

**Comment by aandrew-me** [comment] 2024-02-23 07:04
I found that there is a problem, working on it

**Comment by aandrew-me** [comment] 2024-02-23 11:45
Let me know how it is in the latest update

**Comment by splace** [comment] 2024-02-24 16:11
latest (.2) now shows requested size.

**Comment by splace** [comment] 2024-02-24 16:21
....but still highlights the wrong codec, which is invisible without details being turned on.
![image](https://github.com/aandrew-me/ytDownloader/assets/1234848/390432aa-7de2-477c-acae-da53243862ba)

**Comment by aandrew-me** [comment] 2024-02-24 16:23
What's your preferred video codec?

**Comment by splace** [comment] 2024-02-24 16:25
maybe automatically turn on the details? when there is ambiguity.

**Comment by splace** [comment] 2024-02-24 16:26
> What's your preferred video codec?

not changed "avc1"

**Comment by aandrew-me** [comment] 2024-02-24 16:27
I don't get it. Your preferred video codec is avc1, and program selects avc1 too. Where is the problem?

**Comment by splace** [comment] 2024-02-24 16:34
> I don't get it. Your preferred video codec is avc1, and program selects avc1 too. Where is the problem?

my image shows vp09 is selected
are you only looking at the drop down options showing avc1 is available?

**Comment by aandrew-me** [comment] 2024-02-24 16:38
My bad, missed it.

Strange, fine on my side

<img width="834" alt="image" src="https://github.com/aandrew-me/ytDownloader/assets/66430340/b51c49f7-6685-458c-8d2d-32536749ce60">

**Comment by splace** [comment] 2024-02-24 16:42
i suppose different regions might get different options.

what does your drop-down show?

**Comment by aandrew-me** [comment] 2024-02-24 16:48
Can you do a screen video showing you selecting avc1 codec in preferences and then getting video info?

**Comment by splace** [comment] 2024-02-24 16:49
ummm, 
i restarted and now get correct selected, which means its something not being reset between downloads.

**Comment by aandrew-me** [comment] 2024-02-24 16:51
It should get correctly selected in between downloads

**Comment by splace** [comment] 2024-02-24 16:52
yes, but it didn't.

**Comment by aandrew-me** [comment] 2024-02-24 16:52
Maybe you were still using the old version

**Comment by aandrew-me** [comment] 2024-02-24 16:53
See if there are still problems now, if not all is good

**Comment by splace** [comment] 2024-02-24 16:55
> Maybe you were still using the old version

no, updated last night.

**Comment by splace** [comment] 2024-02-24 17:06
> See if there are still problems now, if not all is good

thats delusionally optimistic

**Comment by splace** [comment] 2024-02-24 17:07
OK, downloaded, then did another, and i comes up wrong, what a surprise!

**Comment by splace** [comment] 2024-02-24 17:08
are you fixing or going to ignore, this feels like a waste of my time now.

**Comment by aandrew-me** [comment] 2024-02-24 17:15
I am trying to the the problem for you and you feel like its a waste of your time, the irony!

**Comment by aandrew-me** [comment] 2024-02-24 17:27
> OK, downloaded, then did another, and i comes up wrong, what a surprise!

Did the same, but the correct format was selected, at this point i think its better to close it

**Closed by aandrew-me** 2024-02-24 17:27 UTC
Labels: bug, Added to source code
